---

version: '3'

services:

  sut:
    build:
      context: services/app
      dockerfile: Dockerfile
    command: mix test
    # env_file: '.env'
    environment:
  depends_on:
    - db
  db:
    image: postgres:9.6
