name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Prepare ansible
        run: make docker-ansible-build-image
      - name: Generate Env
        run: make project-env-generate
      - name: Run tests
        run: |
          docker-compose --file docker-compose.test.yml run sut
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

