name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # - run: apt install make
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          make project-env-generate
          docker-compose --file docker-compose.test.yml run sut
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

